INSERT INTO dishes (name, price_eur) VALUES
  ('Planche mixte charcuterie et fromage', 21.50),
  ('Camembert roti au miel, toasts, charcuterie', 20.00),
  ('Oignons rings', 6.50),
  ('Croquettes de Camembert pannées', 7.50),
  ('Salade aux scampis', 20.00),
  ('Salade Grecque (small)', 12.00),  
  ('Salade Grecque (large)', 18.00),
  ('Salade Chevre Chaud au Miel (small)', 12.00),
  ('Salade Chevre Chaud au Miel (large)', 18.00),
  ('Tartare de saumon frais et avocat', 22.00),
  ('Burger Saumon Frais', 21.50),
  ('Chicken Crispi Burger', 20.50),
  ('Burger Vegetarien', 20.50),
  ('Burger Pulled Porc', 21.50),
  ('Bouchee a la Reine Maison', 24.00),  
  ('Cordon bleu Maison', 20.50),
  ('Filet de poulet', 19.50),
  ('Ham, Fritten an Zalot', 20.50),
  ('Carpaccio de boeuf', 19.50),
  ('Ribs de porc', 21.5),
  ('Cafe gourmand (Macarons, mini creme brulee, brownie)', 10.50),
  ('Coeur fondant au chocolat Maison avec glace vanille', 9.00),
  ('Selection de glaces et sorbets - 1 boule', 3.00),
  ('Tarte aux pommes et sa glace vanille', 8.00)  
;
